language: node_js
#long term servicing version
node_js:
  - lts/*
# ubuntu 18.04 bionic
dist: bionic
env:
  global:
    #enable firefox headless mode for faster automated UI testing
    - MOZ_HEADLESS=1
addons:
  #installs firefox
  firefox: latest
  #installs sonarcloud
  sonarcloud:
    organization: 'AlexanderSarson'
    token:
      secure: 'Dwc9UgvXwuZsPMg/P0OrtVzF1yoRhLhT5RHRRXiS/JxbEiwOgonCBl2OO2dOPRC2cMMfsaQ0HTzGpRRjLZL7/LtMGbEKa5zoAuIy2kyURWB36EV752w9HpTEXvO3hhvZPD22os5tIoR2u0APRNJi/Ew8Yp5+DVyV3EY014zBMvC5wtLAjHQg8HDGDxO0rYXLU7kT6w/K8Kvsq2gkFPVBTS7qb0b3IMQg5rFUyztqzAvB2LxbCugz3Q/hPufHm4bZBCGkKzL0PGWFZ6/dFcl+3SWvAkUtuhIHppZWk4v0FmKANDY83Y7mKIvKx9V/ZWF7B++S/BFI4QgfFcrhtQSHjtFMgaW9GSQKUELwjY/auYEkPZ+OR1fq4AHBNwc/C4wOVTO20eZKuj0jLbDCWi3kLkefgc7jx7witRu8dxB0DSKTMXzrXjwdLCZs5EdOUSE9WaKJWQjSiwxNcczP5uberkz3HdWYDLQtw/3Q9yPmcKxmr44keufJJZxb0gWSfU8lzuHpcKuDmR2vQA6cKA2XC41S6KEeeiTc4Zqryh3QYzJjuwK88UcWhjBRuY4x07QzgmvkVkJwHLBf3S5iJTD8SpQ48qHd5KXpaWeuqxR0apc0i+2vaaqc1fm5ToqNtjmgI3u0c4jCK5GCtCIVDaBivCsf58utMFvrKTD3/Zjiqyc='
  apt:
    packages:
      #Cypress dependency on linux
      - libgconf-2-4
cache:
  directories:
    #Cypress cache
    - '~/.cache'
install:
  #Like npm install but used in automated environments to make sure it does a clean install of dependencies and it can be significantly faster. (you must have a package-lock.json)
  - npm ci

script:
  #start and wait for webpack dev server
  - npm run start:ci & wait-on http://localhost:3000
  #automated UI tests which records testing to cypress dashboard
  - npm run cy:ci:test
  #sonar analyze code from repo and coverage from cypress
  - sonar-scanner
  - npm run build
  #Deploy will only run on master branch. Deploys to surge - must have provided login details on travis-org/travis.com for this to work.
deploy:
  provider: surge
  project: './build/'
  domain: https://recipes-frontend.surge.sh
  skip_cleanup: true
