export const cuisines = [
  { key: 'it', value: 'Italian', text: 'Italian', flag: 'it' },
  { key: 'dk', value: 'Danish', text: 'Danish', flag: 'dk' },
  { key: 'af', value: 'African', text: 'African', flag: 'za' },
  { key: 'us', value: 'American', text: 'American', flag: 'us' },
  { key: 'uk', value: 'British', text: 'British', flag: 'uk' },
  { key: 'ca', value: 'Cajun', text: 'Cajun', flag: 'eu' },
  { key: 'cb', value: 'Caribbean', text: 'Caribbean', flag: 'bs' },
  { key: 'cn', value: 'Chinese', text: 'Chinese', flag: 'cn' },
  {
    key: 'ee',
    value: 'Eastern European',
    text: 'Eastern European',
    flag: 'eu'
  },
  { key: 'eu', value: 'European', text: 'European', flag: 'eu' },
  { key: 'fr', value: 'French', text: 'French', flag: 'fr' },
  { key: 'de', value: 'German', text: 'German', flag: 'de' },
  { key: 'gr', value: 'Greek', text: 'Greek', flag: 'gr' },
  { key: 'in', value: 'Indian', text: 'Indian', flag: 'in' },
  { key: 'ie', value: 'Irish', text: 'Irish', flag: 'ie' },
  { key: 'jp', value: 'Japanese', text: 'Japanese', flag: 'jp' },
  { key: 'il', value: 'Jewish', text: 'Jewish', flag: 'il' },
  { key: 'kr', value: 'Korean', text: 'Korean', flag: 'kr' },
  { key: 'co', value: 'Latin American', text: 'Latin American', flag: 'co' },
  { key: 'hr', value: 'Mediterranean', text: 'Mediterranean', flag: 'hr' },
  { key: 'mx', value: 'Mexican', text: 'Mexican', flag: 'mx' },
  { key: 'ir', value: 'Middle Eastern', text: 'Middle Eastern', flag: 'ir' },
  { key: 'no', value: 'Nordic', text: 'Nordic', flag: 'dk' },
  { key: 'sc', value: 'Southern', text: 'Southern', flag: 'sc' },
  { key: 'es', value: 'Spanish', text: 'Spanish', flag: 'es' },
  { key: 'th', value: 'Thai', text: 'Thai', flag: 'th' },
  { key: 'vn', value: 'Vietnamese', text: 'Vietnamese', flag: 'vn' }
];
